//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusBookingProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chitietdatve
    {
        public int MaKH { get; set; }
        public int MaVe { get; set; }
        public string PhuongThucThanhToan { get; set; }
    
        public virtual Khach_Hang Khach_Hang { get; set; }
        public virtual Ve_Xe Ve_Xe { get; set; }
    }
}
