//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusBookingProject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BusTicketManagementEntities : DbContext
    {
        public BusTicketManagementEntities()
            : base("name=BusTicketManagementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Chitietdatve> Chitietdatves { get; set; }
        public virtual DbSet<Chuyen_Xe> Chuyen_Xe { get; set; }
        public virtual DbSet<Khach_Hang> Khach_Hang { get; set; }
        public virtual DbSet<Loai_KhachHang> Loai_KhachHang { get; set; }
        public virtual DbSet<Loai_NV> Loai_NV { get; set; }
        public virtual DbSet<Loai_Xe> Loai_Xe { get; set; }
        public virtual DbSet<Nhan_Vien> Nhan_Vien { get; set; }
        public virtual DbSet<Tai_Xe> Tai_Xe { get; set; }
        public virtual DbSet<Tuyen_Xe> Tuyen_Xe { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Ve_Xe> Ve_Xe { get; set; }
        public virtual DbSet<Xe> Xes { get; set; }

    }
}
