//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusBookingProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ve_Xe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ve_Xe()
        {
            this.Chitietdatves = new HashSet<Chitietdatve>();
        }
    
        public int MaVe { get; set; }
        public string TenVe { get; set; }
        public Nullable<int> MaNV { get; set; }
        public Nullable<int> MaChuyenXe { get; set; }
        public Nullable<int> MaXe { get; set; }
        public string ViTriGheNgoi { get; set; }
        public string GhiChu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Chitietdatve> Chitietdatves { get; set; }
        public virtual Chuyen_Xe Chuyen_Xe { get; set; }
        public virtual Nhan_Vien Nhan_Vien { get; set; }
        public virtual Xe Xe { get; set; }
    }
}
